version: "3.2"
services:
  database:
    container_name: database-mysql
    image: mysql:5.7
    ports:
      - "${DATABASE_EXPOSED_PORT}:${DATABASE_CONTAINER_PORT}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    networks:
      - fullstack

  api:
    image: node:alpine
    container_name: api-node
    depends_on:
      - database
    ports:
      - "${API_EXPOSED_PORT}:${API_CONTAINER_PORT}"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start:dev
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
